---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - dns.hanzo.ai
  resources:
  - dnsrecords
  - dnszones
  - pagesprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.hanzo.ai
  resources:
  - dnsrecords/status
  - dnszones/status
  - pagesprojects/status
  verbs:
  - get
  - patch
  - update
